services:
  - type: web
    name: my-node-app
    runtime: node
    buildCommand: "npm install"
    startCommand: "node index.js"
    envVars:
      - key: NODE_ENV
        value: production
    plan: free
